services:

  gateway-server:
    container_name: gateway-server
    build: ./gateway-server/target
    ports:
      - "8761:8761"
    expose:
      - "8761"



  eureka-server:
    build: ./eureka-server/target
    container_name: eureka-server
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      DISCOVERY_SERVICE_URL: http://eureka-server:8761/eureka/


  profile:
    container_name: profile
    build: ./profile/target
    ports:
      - "8082:8082"
    expose:
      - "8082"


  portfolio:
    container_name: portfolio
    build: ./portfolio/target
    ports:
      - "8081:8081"
    expose:
      - "8081"




