server:
  port: 8082

spring:
  cloud:
    config:
      enabled: false

  application:
    name: SERVICE-PORTFOLIO

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/essabarrportfolio?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
